# Generated by Django 2.1 on 2018-08-29 12:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencesToLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Переход по ссылке',
                'verbose_name_plural': 'Переходы по ссылкам',
                'ordering': ['-add_date'],
            },
        ),
        migrations.CreateModel(
            name='ShortcutRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_url', models.URLField(verbose_name='Реальная ссылка')),
                ('short_url', models.URLField(verbose_name='Короткая ссылка')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('max_following', models.PositiveIntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Количество переходов')),
                ('active', models.BooleanField(default=True, verbose_name='активность')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
                'ordering': ['-add_date', 'real_url'],
            },
        ),
        migrations.AddField(
            model_name='referencestolinks',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.ShortcutRef', verbose_name='Родитель'),
        ),
    ]
